name: snow
description: Aplicación de organización académica Snow.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2
  intl: ^0.20.3
  audioplayers: ^6.4.0
  file_saver: ^0.3.1
  pdf: ^3.11.3
  google_mobile_ads: ^9.0.0
  in_app_purchase: ^3.3.0
  flutter_markdown_plus: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/sounds/ding.mp3
    - assets/icon/snow_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/snow_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#5A46F5"
  min_sdk_android: 21